modLoader="javafml"
loaderVersion="[35,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/JustEnoughAdvancements/issues/"

[[mods]]
modId="jea"
version="${file.jarVersion}"
displayName="Just Enough Advancements"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/jea.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="jea.png"
credits=""
authors="MelanX, noeppi_noeppi"
description='''
An addon for JEI to view advancements.
'''

[[dependencies.jea]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"

[[dependencies.jea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"

[[dependencies.jea]]
    modId="jei"
    mandatory=true
    versionRange="[7.6.0.58,)"

[[dependencies.jea]]
    modId="libx"
    mandatory=true
    versionRange="[1.16.3-1.0.63,)"

[[dependencies.jea]]
    modId="botania"
    mandatory=false
    versionRange="[1.16.5-415,)"

[[dependencies.jea]]
    modId="botania"
    mandatory=false
    versionRange="[1.16.4-1.3.5,)"