modLoader="javafml"
loaderVersion="[45,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/JustEnoughAdvancements/issues/"

[[mods]]
    modId="jea"
    version="${file.jarVersion}"
    displayName="Just Enough Advancements"
    updateJSONURL="https://assets.melanx.de/updates/jea.json"
    displayURL="www.curseforge.com/members/melanx/"
    credits=""
    authors="MelanX, noeppi_noeppi"
    description="An addon for JEI to view advancements."

[[dependencies.jea]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"

[[dependencies.jea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,)"

[[dependencies.jea]]
    modId="jei"
    mandatory=true
    versionRange="[12.3.0.18,)"

[[dependencies.jea]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.4-4.4.0,)"
