modLoader="javafml"
loaderVersion="[37,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/JustEnoughAdvancements/issues/"

[[mods]]
modId="jea"
version="${file.jarVersion}"
displayName="Just Enough Advancements"
updateJSONURL="https://assets.melanx.de/updates/jea.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="jea.png"
credits=""
authors="MelanX, noeppi_noeppi"
description='''
An addon for JEI to view advancements.
'''

[[dependencies.jea]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.15,)"

[[dependencies.jea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"

[[dependencies.jea]]
    modId="jei"
    mandatory=true
    versionRange="[9.0.0.40,)"

[[dependencies.jea]]
    modId="libx"
    mandatory=true
    versionRange="[1.18-3.0.0,)"

#[[dependencies.jea]]
#    modId="botania"
#    mandatory=false
#    versionRange="[1.16.5-415,)"
#
#[[dependencies.jea]]
#    modId="mythicbotany"
#    mandatory=false
#    versionRange="[1.16.4-1.3.5,)"