modLoader="javafml"
loaderVersion="[40,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/JustEnoughAdvancements/issues/"

[[mods]]
modId="jea"
version="${file.jarVersion}"
displayName="Just Enough Advancements"
updateJSONURL="https://assets.melanx.de/updates/jea.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="jea.png"
credits=""
authors="MelanX, noeppi_noeppi"
description='''
An addon for JEI to view advancements.
'''

[[dependencies.jea]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.12,)"

[[dependencies.jea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"

[[dependencies.jea]]
    modId="jei"
    mandatory=true
    versionRange="[9.4.3.123,)"

[[dependencies.jea]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.1,)"
