modLoader="javafml"
loaderVersion="[41,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/JustEnoughAdvancements/issues/"

[[mods]]
modId="jea"
version="${file.jarVersion}"
displayName="Just Enough Advancements"
updateJSONURL="https://assets.melanx.de/updates/jea.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="jea.png"
credits=""
authors="MelanX, noeppi_noeppi"
description='''
An addon for JEI to view advancements.
'''

[[dependencies.jea]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.33,)"

[[dependencies.jea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"

[[dependencies.jea]]
    modId="jei"
    mandatory=true
    versionRange="[11.0.0.206,)"

[[dependencies.jea]]
    modId="libx"
    mandatory=true
    versionRange="[1.19-4.0.2,)"
