modLoader="javafml"
loaderVersion="[47,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/JustEnoughAdvancements/issues/"

[[mods]]
modId="jea"
version="${version}"
displayName="Just Enough Advancements"
updateJSONURL="https://assets.melanx.de/updates/jea.json"
displayURL="www.curseforge.com/members/melanx/"
credits=""
authors="MelanX, noeppi_noeppi"
description='''
An addon for JEI to view advancements.
'''

[[dependencies.jea]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.3,)"

[[dependencies.jea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"

[[dependencies.jea]]
    modId="jei"
    mandatory=true
    versionRange="[15.0.0.12,)"

[[dependencies.jea]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.1,)"
