modLoader="javafml"
loaderVersion="[35,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/AdvancementBook/issues/"

[[mods]]
modId="advancementbook"
version="${file.jarVersion}"
displayName="Advancement Book"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/advancementbook.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="modid.png"
credits=""
authors="MelanX"
description='''

'''

[[dependencies.advancementbook]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"

[[dependencies.advancementbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17)"

[[dependencies.advancementbook]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-48,)"